Introduce new class Controls(), used to store the controls of a device. This class extends dict() in order to allow accessing a certain control not only by its ID, but also by its config_name - in a backward compatible way, without requiring changes to existing code. Example:
```python
>>> from v4l2py import Device
>>> cam = Device.from_id(0)
>>> cam.open()
>>> for c in cam.controls.values():
...     print(c)
...
<Control brightness type=integer min=0 max=255 step=1 default=128 value=128>
<Control contrast type=integer min=0 max=255 step=1 default=32 value=32>
...
<Control exposure_time_absolute type=integer min=10 max=333 step=1 default=156 value=156 flags=inactive>
<Control exposure_dynamic_framerate type=boolean default=0 value=1>
>>>
>>> cam.controls["brightness"]
<Control brightness type=integer min=0 max=255 step=1 default=128 value=128>
>>> cam.controls.brightness
<Control brightness type=integer min=0 max=255 step=1 default=128 value=128>
>>>
>>> cam.controls.brightness.value = 64
>>> cam.controls.brightness
<Control brightness type=integer min=0 max=255 step=1 default=128 value=64>
>>>
>>> cam.controls.doesnotexist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/src/v4l2py-o42/v4l2py/device.py", line 773, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{key}'")
AttributeError: 'Controls' object has no attribute 'doesnotexist'
>>> cam.controls["doesnotexist"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/src/v4l2py-o42/v4l2py/device.py", line 788, in __missing__
    raise KeyError(key)
KeyError: 'doesnotexist'
````